language: ruby
rvm: 2.6.6
cache: bundler
before_install:
 - gem install bundler
 - nvm install --lts
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rake test
services: postgresql
dist: trusty
addons:
  postgresql: "13.2"
deploy:
  provider: heroku
  api_key:
    secure: MVZ+o6KpBgZqNL+lo4+R38KviPB4UWB1BAfsGXXXBmiORcthE5eNjil76LTeus3OZ6auDSxZB2cQXp3Rs2BJlrXjzDp3kTLAZW0HOu4KcgkfL8s4wOet5rTVtrpbKiAt+eFFYViXxMmGKJY/Wg4eTi1Kvexbj+4xXkQJd5zXsb3uZivxJCI0fUDfhrEp7U9iidktRQVC5sTzgl6OQFPe94b++vCFkFjL36sEkws5AWJwkxbLv/4En+3TBsSqQoQQwA6b3I0+esZRLj9RZdXEAumBKVXldX/009iYzT5GwQ9CtD8Qh9/cCDXFUiaVFIwBRvM4hMBz6sBvGduBpGL2vQT7HOuggvY+EAMcQanPWWOhAvinYrbTnBsxljB8Rtgv4gEDRhyeb+OAno4Z4X0t80/yEZ6AbsbUc8P+D5X+8HNVDo10wjv96ku5XzXoZDUR51mI+O3CuYeKmrI/oq9GHH6531hKW/WreT5AnHUsx5djqnkYrtLUKymw7D4TpSx51aTsBh62WNVcX0nWWBKoTjcm5ZpGMdO5CrqTfWph/fQFG3F6KnUtMMNCLEf4IsSdCfcL/D89toxydiJVsqZruuqKSec6OxsU6B5IllHFg1ch21B1HyWeOISr+eMK5i6gNO8sSXC5fyWwlc8LPl7aX+HZSHHK0z5s7YR8x86NnCk=
  app: kahla_consulting
